server:
  port: 8099

spring:
  # 配置数据源，如果不指定连接池，springboot默认配置了HikariPool连接池
  datasource:
    url: jdbc:mysql://localhost:3306/white_jotter?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis
  redis:
    host: localhost
    port: 6379
    password: root
    lettuce:
      pool:
        # 连接池最大数，默认是8
        max-active: 8
        # 连接池最大阻塞等待时间，默认是-1（负数表示没有时间限制）
        max-wait: -1
        # 连接池中的最大空闲连接，默认是8
        max-idle: 8
        # 连接池中的最小空闲连接，默认是0
        min-idle: 0


mybatis:
  mapper-locations: classpath:mappers/*.xml
  # spring boot集成mybatis的方式打印sql到控制台
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

